#!/bin/bash
# .git/hooks/commit-msg

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Simple regex for Conventional Commits
if ! echo "$commit_msg" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|ops)(\(.+\))?: .{1,50}"; then
  echo "Commit message format is incorrect. It should be: <type>(<scope>): <subject>"
  echo "Example: feat(auth): add login functionality"
  exit 1
fi
